name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Build
        run: cd frontend && npm run build
        env:
          VITE_FIREBASE_API_KEY: AIzaSyAO9ISI7acZUs-PaKTNylOoe2k_cS4q-nE
          VITE_FIREBASE_AUTH_DOMAIN: iluminariasuce.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID: iluminariasuce
          VITE_FIREBASE_STORAGE_BUCKET: iluminariasuce.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID: "741308647563"
          VITE_FIREBASE_APP_ID: 1:741308647563:web:4932538ddf256fc1c1ac8e
          VITE_USE_FIREBASE_EMULATOR: "false"
          VITE_API_URL: https://iluminarias-api.onrender.com/api
          VITE_ANALYTICS_URL: https://iluminarias-analytics.onrender.com
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ILUMINARIASUCE }}
          projectId: iluminariasuce
